import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Privacy Policy — Signal Guard",
};

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 py-24 pt-32 text-slate-300">
      <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-slate-500 text-sm mb-12">Last updated: May 2025</p>

      <section className="space-y-10 text-sm leading-relaxed">

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">1. Who We Are</h2>
          <p>
            Signal Guard is a service operated by Umut Çakmak ("we", "us", or "our"),
            based in Turkey. You can reach us at{" "}
            <a href="mailto:data@umutcakmak.com" className="text-indigo-400 hover:underline">
              data@umutcakmak.com
            </a>.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">2. What Data We Collect</h2>
          <ul className="list-disc pl-5 space-y-2 text-slate-400">
            <li>
              <strong className="text-slate-200">Account information:</strong> Your name and email
              address, collected when you sign in via Google or magic link.
            </li>
            <li>
              <strong className="text-slate-200">Google OAuth token:</strong> A refresh token that
              allows Signal Guard to query your Google BigQuery datasets on your behalf. This token
              is encrypted at rest using AES-256-GCM.
            </li>
            <li>
              <strong className="text-slate-200">Guard configuration:</strong> The GCP project IDs,
              BigQuery dataset IDs, event names, and notification preferences you enter when creating
              guards.
            </li>
            <li>
              <strong className="text-slate-200">Run results:</strong> Anomaly detection results
              (event counts, drop percentages) generated by your guards. No raw GA4 event data is
              stored — only aggregated counts.
            </li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Data</h2>
          <ul className="list-disc pl-5 space-y-2 text-slate-400">
            <li>To authenticate you and maintain your session.</li>
            <li>To query your BigQuery datasets and detect anomalies in your GA4 data.</li>
            <li>To send email or Slack alerts when anomalies are detected.</li>
            <li>To display your guard history and run results in the dashboard.</li>
          </ul>
          <p className="mt-3 text-slate-400">
            We do not sell your data to third parties. We do not use your data for advertising.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">4. Google API Scopes</h2>
          <p className="text-slate-400">
            Signal Guard requests the following Google OAuth scopes:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-slate-400 mt-2">
            <li>
              <code className="text-indigo-300">https://www.googleapis.com/auth/bigquery.readonly</code>{" "}
              — read-only access to your BigQuery datasets to query GA4 event tables.
            </li>
            <li>
              <code className="text-indigo-300">openid</code>,{" "}
              <code className="text-indigo-300">email</code>,{" "}
              <code className="text-indigo-300">profile</code> — basic identity for authentication.
            </li>
          </ul>
          <p className="mt-3 text-slate-400">
            We do not request write access to your Google account or BigQuery projects.
            You can revoke access at any time from your{" "}
            <a
              href="https://myaccount.google.com/permissions"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              Google account permissions
            </a>.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">5. Data Storage & Security</h2>
          <p className="text-slate-400">
            Your data is stored in a PostgreSQL database hosted on Supabase (EU region). Google
            OAuth refresh tokens are encrypted at rest using AES-256-GCM before storage. We use
            HTTPS for all data in transit.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">6. Data Retention</h2>
          <p className="text-slate-400">
            Your data is retained for as long as your account is active. You may request deletion
            of your account and all associated data at any time by emailing{" "}
            <a href="mailto:data@umutcakmak.com" className="text-indigo-400 hover:underline">
              data@umutcakmak.com
            </a>.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">7. Third-Party Services</h2>
          <ul className="list-disc pl-5 space-y-2 text-slate-400">
            <li><strong className="text-slate-200">Vercel</strong> — application hosting (USA/EU)</li>
            <li><strong className="text-slate-200">Supabase</strong> — database hosting (EU)</li>
            <li><strong className="text-slate-200">Resend</strong> — transactional email delivery</li>
            <li><strong className="text-slate-200">Google Cloud</strong> — authentication and BigQuery access</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">8. Your Rights</h2>
          <p className="text-slate-400">
            Under applicable laws (including GDPR and KVKK), you have the right to access,
            correct, or delete your personal data. To exercise these rights, contact us at{" "}
            <a href="mailto:data@umutcakmak.com" className="text-indigo-400 hover:underline">
              data@umutcakmak.com
            </a>.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">9. Changes to This Policy</h2>
          <p className="text-slate-400">
            We may update this policy from time to time. We will notify you of significant changes
            via email or a notice in the dashboard.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
          <p className="text-slate-400">
            Questions about this policy? Email us at{" "}
            <a href="mailto:data@umutcakmak.com" className="text-indigo-400 hover:underline">
              data@umutcakmak.com
            </a>.
          </p>
        </div>

      </section>
    </main>
    <Footer />
    </>
  );
}
